allow_k8s_contexts(['orbstack', 'docker-desktop'])

load('ext://dotenv', 'dotenv')

is_prod = os.getenv('PROD') == 'true'

# Disable analytics in local development
os.putenv('NEXT_PUBLIC_ARCHESTRA_ANALYTICS', "disabled")

# set NEXT_PUBLIC_ARCHESTRA_API_BASE_URL to the same value as ARCHESTRA_API_BASE_URL
# so it's accessible by the frontend
api_base_url = os.getenv("ARCHESTRA_API_BASE_URL")
next_pubic_api_base_url = os.getenv("NEXT_PUBLIC_ARCHESTRA_API_BASE_URL")
if not next_pubic_api_base_url and api_base_url and api_base_url != "":
  os.putenv('NEXT_PUBLIC_ARCHESTRA_API_BASE_URL', api_base_url)

# Check if .env exists, if not copy from .env.example
if not os.path.exists('.env'):
  local('cp .env.example .env')
  print("📝 Created .env from .env.example, be sure to fill in any necessary unique values (ex. API keys)")
else:
  print("📝 .env already exists, skipping copy from .env.example")

dotenv('./.env')

# Load sub-Tiltfiles by label
load_dynamic('./dev/Tiltfile.database')
load_dynamic('./dev/Tiltfile.dev')
load_dynamic('./dev/Tiltfile.test')
load_dynamic('./dev/Tiltfile.integrations')
